module.exports = {
  basics: {
    name: '',
    label: '',
    picture: '',
    email: '',
    phone: '',
    website: '',
    summary: '',
    location: {
      address: '',
      postalCode: '',
      city: '',
      countryCode: '',
      region: '',
    },
    profiles: [],
  },
  work: [],
  volunteer: [],
  education: [],
  awards: [],
  publications: [],
  skills: [],
  languages: [],
  interests: [],
  references: [],
};
